version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(api-deps)"
