# permissions for end users to view cfnstacks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfnstack-viewer-role
rules:
- apiGroups:
  - cloudformation.contrib.fluxcd.io
  resources:
  - cfnstacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudformation.contrib.fluxcd.io
  resources:
  - cfnstacks/status
  verbs:
  - get
