apiVersion: cloudformation.contrib.fluxcd.io/v1alpha1
kind: CloudFormationStack
metadata:
  name: my-other-cfn-stack
  namespace: flux-system
spec:
  stackName: my-other-cfn-stack-deployed-by-flux
  templatePath: ./another-template.yaml
  sourceRef:
    kind: GitRepository
    name: my-cfn-templates-repo
  interval: 1h
  retryInterval: 5m
  destroyStackOnDeletion: true
