apiVersion: v1
kind: ServiceAccount
metadata:
  name: cfn-controller
  namespace: system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/AWSCloudFormationControllerFluxIRSARole
